server:
  port: 8888

spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          default-label: master # default branch 설정
          uri: file://d:\\study\spring\springcloud01-msa\_config\config